== Файлы конфигураций

Файлы конфигураций - это основной способ конструирования интерфейса и связей с данными на N2O.

=== Расположение

Файлы конфигураций распологаются в папке ресурсов модуля или проекта: `src/main/resources/META-INF/conf`.

Любой файл из этой папки может быть переопределен одноименным файлом в папке расширений.
Путь к папке расширений задаётся link:#_Настройки_и_локализация[настройкой] `n2o.config.path`. По умолчанию: `[USER_HOME]/.n2o/conf`.

=== Формат файла

Файлы конфигураций имеют определенный формат имени файла:
----
[id].[type].[ext]
----
`id`:: Уникальный идентификатор метаданной в рамках типа
`type`:: Тип метаданной
`ext`:: Способ задания метаданной (`.xml` или `.groovy`)

=== Типы метаданных

.Типы метаданных
[cols="1,1,4,2"]
|===
|Тип |Описание |XML Схема|Класс метаданной

|page
|Страница
|http://n2oapp.net/framework/config/schema/page-2.0
|N2oPage

|widget
|Виджет
|http://n2oapp.net/framework/config/schema/widget-4.0
|N2oWidget

|object
|Объект
|http://n2oapp.net/framework/config/schema/object-2.0
|N2oObject

|query
|Выборка
|http://n2oapp.net/framework/config/schema/query-4.0
|N2oQuery

|fieldset
|Филдсет
|http://n2oapp.net/framework/config/schema/fieldset-4.0
|N2oFieldSet

|header
|Хедер
|http://n2oapp.net/framework/config/schema/simple-header-1.0
|N2oHeader

|menu
|Меню
|http://n2oapp.net/framework/config/schema/menu-1.0
|N2oSimpleMenu

|access
|Схема доступа
|http://n2oapp.net/framework/config/schema/access-1.0
|N2oAccessSchema
|===


=== Структура XML файла

В теле XML файла первой строчкой должен идти заголовок `xml`:
[source,xml]
----
<?xml version='1.0' encoding='UTF-8'?>
----

Далее корневой элемент метаданной и XML схема, определяющая её структуру:
[source,xml]
----
<?xml version='1.0' encoding='UTF-8'?>
<object xmlns="http://n2oapp.net/framework/config/schema/object-3.0">
  ...
</object>
----

[NOTE]
В наименовании схемы содержится её версия. Это позволяет схемам эволюционировать с полным сохранением обратной совместимости.

=== Структура Groovy файла
Файлы конфигураций можно создавать с помощью http://groovy-lang.org/[groovy] скриптов.
Это может пригодиться для создания однообразных метаданных.

Для подключения groovy необходимо добавить зависимость:
[source,xml]
----
<dependency>
  <groupId>org.codehaus.groovy</groupId>
  <artifactId>groovy-all</artifactId>
</dependency>
----

.Пример файла myForm.widget.groovy
[source,javaScript]
----
import net.n2oapp.framework.api.metadata.global.view.widget.N2oForm

form = new N2oForm()
form.name = 'Форма на groovy'
----
В groovy скрипте необходимо просто создать объект метаданной, соответствующей её link:#_Типы_метаданных[типу].

[IMPORTANT]
Объявлять переменную метаданной через директиву `def` или имя класса не нужно!
Иначе она будет локальной, и N2O её не "увидит".


=== Ссылки на другие файлы

Метаданные часто связаны между собой.
Для ссылки на связанные метаданные используются элементы или атрибуты XML с окончанием: `-id`.
В качестве значения ссылки используется идентификатор метаданной:
[source,xml]
----
<query object-id="myObject">
  ...
</query>
----

=== Библиотеки компонентов

Внутри некоторых XML элементов позволяется вставлять элементы из другой схемы:
[source,xml]
----
<set xmlns="http://n2oapp.net/framework/config/schema/fieldset-4.0"
     xmlns:ctrl="http://n2oapp.net/framework/config/schema/control-2.0">
  <ctrl:input-text>...</ctrl:input-text>
</set>
----
Такие места называются местами подключения библиотек компонентов.

[WARNING]
====
Не во всех местах допускается подключение библиотеки компонентов.
Чтобы не ошибиться, необходимо смотреть схему элемента.
В схеме элемента, допускающего библиотеки расширения, должен стоять элемент:
`<xs:any namespace="##other"/>`
====

=== Вложенные метаданные

Внутри некоторых XML элементов используются вложенные метаданные другого типа.

Например, есть страница `<page>` с таблицей `<table>` внутри.
Таблица - это виджет, который задаётся отдельным xml файлом. Его можно задать и внутри страницы:

[source,xml]
----
<simple-page>
  <table>
    <!-- Элементы вложенного виджета таблица -->
    <columns>...</columns>
    ...
  </table>
</simple-page>
----
Либо можно сослаться на внешний файл используя атрибут `ref-id`:
[source,xml]
----
<simple-page>
  <table ref-id="myTable"/>
</simple-page>
----

=== Переопределение свойств

Во вложенных метаданных можно переопределить некоторые свойства метаданной, заданной по ссылке:
[source,xml]
----
<simple-page>
  <table ref-id="myTable" name="Моя таблица">
    <!-- свойство name, заданное здесь, переопределит name, заданный в myTable -->
  </table>
</simple-page>
----

=== Расширенные свойства
В XML-файлы можно добавить свойства, специфичные для прикладного проекта.
Для этого нужно создать XSD схему расширений, подключить её к XML файлу и
вставить атрибуты в те элементы, которые допускают расширения:

.Схема расширений
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://myproject.net/config/schema/ext-props-1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:attribute name="prop1" type="xs:string"/>
    <xs:attribute name="prop2" type="xs:string"/>
</xs:schema>
----

.Подключение схемы расширений
[source,xml]
----
<?xml version='1.0' encoding='UTF-8'?>
<page xmlns="http://n2oapp.net/framework/config/schema/page-2.0"
  xmlns:ext="http://myproject.net/config/schema/ext-props-1.0"
  ext:prop1="value1"
  ext:prop2="value2">
  ...
</page>
----

[WARNING]
Не все элементы XML допускают расширенные свойства.
Чтобы не ошибиться, необходимо смотреть схему элемента.
В схеме элемента, допускающего расширения, должен стоять атрибут:
`<xs:anyAttribute/>`

Расширенные свойства считываются автоматически в свойство `properties` с типом "ключ-значение".
К ним можно получить доступ из link:#_Трансформаторы[трансформации метаданных] или link:#_Процессинг_данных[процессинга данных].

=== Плейсхолдеры
В любых значениях атрибутов и элементов XML можно использовать плейсхолдер `${property}`,
где `property` - это ссылка на link:#_Настройки_и_локализация[настройки и локализацию].

В некоторых атрибутах и элементах (обычно в `value` и `default-value`) допускается использование плейсхолдера `#{context}`,
где `context` - это название свойства в link:#_Контекст[контексте текущего пользователя].

Значения в атрибутах полей формы и ячеек таблицы можно задать с помощью плейсхолдера `{field}`,
где `field` - это ссылка на поле в данных, завязав таким образом link:#_Динамические_свойства[метаданные на данные].

=== Валидация конфигураций
Все файлы конфигураций проверяются на корректность связей и логики.
Проверка инициируется в runtime при первой загрузке файла в приложение.

Если обнаружена ошибка, файл помечается некорректным.
При открытии страницы, связанной с некорректным файлом, отобразится сообщение валидации.
