== Контекст
Контекст пользователя - это любая информация о текущем пользователе приложения.

=== Использование
К контексту пользователя существует быстрый доступ из некоторых мест в XML через "решётку" и фигурные скобки:

[source,xml]
----
<input-text id="login" default-value="#{username}"/>
----

.Места применения контекста в XML
|===
|Место|Описание

|*/[control]/@default-value
|Значение по умолчанию link:#_Значения_по_умолчанию_полей[поля ввода].

|/query/fields/field/filters/[filter-type]/@default-value
|Значение по умолчанию link:#_Фильтры_выборки[фильтра выборки].

|/query/fields/field/select/@default-value
|Значение по умолчанию link:#_Поля_выборки[поля выборки].

|/object/actions/action/in-parameters/param/@default-value
|Значение по умолчанию link:#_Операции_объекта[входящего параметра] операции.

|/object/actions/action/out-parameters/param/@default-value
|Значение по умолчанию link:#_Операции_объекта[исходящего параметра] действия.

|*/pre-filters/[filter-type]/@value
|Значение link:#_Предустановленная_фильтрация[предустановленного фильтра]

|*/pre-fields/[filter-type]/@value
|Значение link:#_Предустановленные_поля[предустановленного поля]

|/access/*/object-access/[filter-type]/@value
|Значение link:#_Схема_доступа[фильтра доступа]

|===

В случае, когда значение контекста отсутствует, возвращается `null`.
Если логика приложения недопускает `null` контекст, можно сделать его обязательным, добавив восклицательный знак в конце:

.Обязательный контекст
[source,xml]
----
<input-text id="name" default-value="#{firstName!}"/>
----

=== Подключение
Контекст подключается автоматически после интеграции с системой аутентификации Spring Security.

[NOTE]
Например, в случае интеграции со Spring Security, все поля объекта `UserDetails` становятся доступны в XML.

Можно сконфигурировать поключение вручную с помощью модульного контекста:

.Подключение модульного контекста в Maven
[source,xml]
----
<dependency>
  <groupId>net.n2oapp.framework</groupId>
  <artifactId>n2o-context</artifactId>
  <version>{version}</version>
</dependency>
----

Модульный контекст позволяет определять параметры контекста в любом jar модуле и получать их значения по первому требованию.
Подключение делается с помощью интерфейса `ContextProvider` зарегистрированного в качестве Spring бина.

[source,java]
----
/**
* Провайдер одного значения контекста
**/
public class MyContextProvider
    implements RootOneValueContextProvider {

    /**
    * @return Значение параметра контекста
    **/
    @Override
    public Object getValue() {
        return "myvalue";
    }

    /**
    * @return Название параметра контекста
    **/
    @Override
    public String getParam() {
        return "myparam";
    }
}
----
