== Значения по умолчанию
Обычно виджеты получают данные с помощью выборки `query-id`.
Но link:#_Загрузка_данных_в_виджет[источником данных] могут быть и значения по умолчанию.
Источник указывается в месте открытия с помощью атрибута `upload`:

.Источник данных при открытии окна
[source,xml]
----
<show-modal page-id="myPage"
  upload="defaults"
  submit-operation-id="create"/>
----

=== Значения по умолчанию полей
Значение по умолчанию в простых полях задаётся атрибутом `default-value`.

.Значение по умолчанию для простых полей
[source,xml]
----
<input-text id="name" default-value="Ваше имя"/>
----

Для списковых полей через элемент `default-value`:

.Значение по умолчанию для списковых полей
[source,xml]
----
<select id="gender">
  <default-value
    id="1"
    name="Мужской"/>
</select>
----

=== Выборка значений по умолчанию
Если значения по умолчанию определяются более сложным образом,
можно использовать выборку `default-values-query-id`:

.Выборка значений по умолчанию
[source,xml]
----
<form default-values-query-id="myDefaults">
  <fields>
    ...
  </fields>
</form>
----

Выборка значений по умолчанию будет запрошена при открытии формы с `upload="defaults"`.
Если поле, которое вернула выборки, пустое, то оно не будет использоваться.
Вместо этого поле заполнится значением по умолчанию из атрибутов `default-value` или элемента `<default-model>`.

=== Вычисляемые значения
Можно задать значение по умолчанию с помощью JavaScript выражения.
В них можно использовать свойства текущей модели виджета как переменные.
Выражения записываются в фигурных скобках:

.Значение по умолчанию в виде JavaScript выражения
[source,xml]
----
<checkbox id="man" default-value="{gender.id == 1}"/>
----

=== Функции дат

Значения по функциям дат и времени записывается аналогично выражениям JavaScript.
Но в качестве выражения задаётся функция:

.Функции даты и времени
[cols="1,4"]
|===
|Функция|Описание

|now()
|Текущая дата и время

|today()
|Текущая дата

|beginWeek()
|Начало недели

|endWeek()
|Конец недели

|beginMonth()
|Начало месяца

|endMonth()
|Конец месяца

|beginQuarter()
|Начало квартала

|endQuarter()
|Конец квартала

|beginYear()
|Начало года

|endYear()
|Конец года

|===

.Значение по умолчанию в виде функции даты и времени
[source,xml]
----
<date-time id="dt" default-value="{now()}"/>
----

=== Форматирование значения
Можно комбинировать константные значения и ссылки.
Такое выражение записывается в обратных апострофах:

.Значение по умолчанию в виде комбинации текста и ссылки
[source,xml]
----
<output-text default-value="Привет, {username}"/>
----
