== Диалоги
В N2o есть возможность использовать диалоги для подтверждения действий пользователя.
Это особенно полезно в ситуацих, когда мы хотим убедиться, что пользователь
точно уверен в выполняемом действии.

=== Настраиваемый диалог
Диалог настраивается таким же образом, что и любой другой тип валидации.
Можно включить его в саму операцию или определить отдельно и указать в операции
в списке `white-list` валидаций.

Отличие диалога от `<constraint>` валидации в наличии настраиваемого тулбара (меню кнопок).
В качестве действий кнопок можно использовать все стандартные действия.
Особенностью здесь является лишь то, что при выполнении действий `<invoke>`
предусмотрено двойное закрытие окон. Таким образом, если вы открыли модальное окно,
из которого вызывается диалоговое окно, то при выполнении действия `<invoke>`
будут закрыты оба.

Вызов диалога возможен в любой момент: до выполнения операции (`before-operation`),
после выполнения успешной (`after-success-operation`) и после операции,
закончившейся ошибкой (`after-fail-operation`).

В случае `before-operation` и `after-success-operation` необходимо использовать
дополнительный параметр, который остановит повторный вызов диалога после
вызова действий в самом диалоге.

В примере ниже используется `validated` параметр и возможность выключить
диалог, если этот параметр задан и его значение `true`. Сам параметр задается
во время вызова действия из диалога, тем самым мы указываем, что повторный вызов
диалога нам не нужен.
[source,xml]
----
<operation id="create">
    <invocation>...</invocation>
    <in>
        ...
        <field id="validated" param="validated"/>
    </in>
    <validations>
        <dialog id="dialog" server-moment="before-operation"
                result="#this &lt; 3"
                enabled="{typeof(validated) === 'undefined' || validated == false}"
                message="Достигнут лимит по количеству пользователей.
                Вы уверены, что хотите добавить еще одного?">
            <invocation>
                ...
            </invocation>
            <toolbar>
                <button id="yes" label="Да">
                    <invoke operation-id="create">
                        <header-param name="validated" value="true"/>
                    </invoke>
                </button>
                <button label="Отмена">
                    <close/>
                </button>
            </toolbar>
        </dialog>
    </validations>
</operation>
----

==== Вызов диалога после операции, закончившейся ошибкой
Диалоги также можно отображать и в случае неудачной работы сервера.
Возможно ошибка произошла из-за некорректных данных, введенных пользователем, и
у нас есть возможность предупредить его об этом.

Для получения данных об ошибке используются `<fail-out>` параметры.
Работают они также, как и `<out>` параметры, только здесь мы с помощью
атрибута `mapping` получаем данные Exception. Эти данные позднее используются
в атрибуте `result` диалога, чтобы проверить предназначен ли диалог для данной ошибки.
[source,xml]
----
<operation id="register">
    <invocation>...</invocation>
    <in>
        <field id="name"/>
        <field id="useExists" param="join"/>
    </in>
    <out>
        ...
    </out>
    <fail-out id="errorMessage" mapping="#this.getMessage()"/>
    <validations>
        <dialog id="dialog" server-moment="after-fail-operation"
                result="!(#this[errorMessage].contains('Пользователь с таким именем уже существует'))"
                message="Joe уже зарегистрирован, что делать?">
            <toolbar>
                <button id="btn1" label="Зарегистрировать нового">
                    <invoke operation-id="register">
                        <header-param name="join" value="false"/>
                    </invoke>
                </button>
                <button id="btn2" label="Использовать существующего">
                    <invoke operation-id="register">
                        <header-param name="join" value="true"/>
                    </invoke>
                </button>
                <button label="Отмена">
                    <close/>
                </button>
            </toolbar>
        </dialog>
    </validations>
</operation>
----
