== Маршрутизация
Каждой странице N2O выдается свой URL адрес.
С помощью маршрутизации можно контролировать формирование URL адресов этих страниц.
В браузезе N2O страницы открываются по следующему URL:
```
http://localhost:8080/#/[route]
```
, где `route` адрес N2O страницы.
Для каждой страницы `route` должен быть уникальным.

Адреса страниц имеют иерархическую структуру.
Если страница вложенная (открывается через `open-page`),
то её адрес будет содержать адрес предыдущей страницы, плюс добавочная часть.

Эта добавочная часть называется маршрутом и задаётся атрибутом `route`.
Маршрут должен начинаться со знака "/", например, `route="/home"`.

Маршрут может содержать параметры пути, которые задаются через двоеточие,
например, `/:master_id/detail`.
Параметр пути указывает на значение идентификатора модели виджета, от которого образована зависимость.
На эти параметры можно ссылаться для получения значений, заданных на предыдущих страницах.

[NOTE]
Т.к. адреса N2O страниц формируются иерархически,
то параметры пути будут сохраняться в адресах всех вложенных страниц.
Следовательно параметры пути должны быть уникальными.
Если они повторяются, то нет смысла их дублировать в адресе.
Будет использоваться значение первого параметра с таким же именем.

=== Маршрутизация в хедере

Начальные адреса страниц задаются в блоке навигации хедера:

[source,xml]
----
<nav>
  <page id="homePage" route="/home">
</nav>
----
link:https://n2oapp.net/sandbox/new/manual/routing/header[Пример]
```
http://localhost:8080/#/home
```
Если `route` не задан, адресом по умолчанию будет id страницы.

Можно указать пустой маршрут `route="/"`, в таком случае страница будет открываться по корневому адресу.

Корневой адрес регистрируется автоматичеки, если задать атрибут `welcome-page-id`:
[source,xml]
----
<nav welcome-page-id="homePage">
  ...
</nav>
----
link:https://n2oapp.net/sandbox/new/manual/routing/header[Пример]
```
http://localhost:8080/#/
```

=== Маршрутизация виджетов

Виджеты могут иметь свою добавочную часть URL, относительно адреса страницы.
Она так же задается атрибутом `route`:
[source,xml]
----
<simple-page>
  <table route="/list">
    ...
  </table>
<simple-page>
----
link:https://n2oapp.net/sandbox/new/manual/routing/widget[Пример]
```
http://localhost:8080/#/list
```

Для основного виджета страницы маршрут по умолчанию отсутствует,
что эквивалентно `route="/"`.
Для остальных случаев, если `route` не задан, маршрутом по умолчанию будет id виджета.

Адрес виджета может содержать параметер пути, который нужен для master/detail фильтрации.
Параметр пути задается в атрибуте `route` через знак ":"

[source,xml]
----
<table id="master" route="/person"
       query-id="person">
  ...<!-- master виджет -->
</table>

<table depends-on="master" route="/:person_id/docs"
       query-id="docs" master-field-id="id" detail-field-id="person.id">
  ...<!-- detail виджет -->
</table>
----
link:https://n2oapp.net/sandbox/new/manual/routing/widget_master_detail[Пример]
```
http://localhost:8080/#/person/123/docs
```

, где `123` значение параметра пути `person_id`,
которое соответствует значению поля `id` выделенной записи таблицы `master`.

Параметр пути может быть только у зависимых виджетов (виджеты с depends-on).
Но его указывать не обязательно.

Если атрибут `route` для зависимого виджета не задан, или задан без указания параметра пути,
то параметр пути будет определяться через атрибут `master-param`:
[source,xml]
----
<table depends-on="master"
       master-param="person_id"
       query-id="docs"
       master-field-id="id" detail-field-id="person.id">
  ...<!-- detail виджет -->
</table>
----

link:https://n2oapp.net/sandbox/new/manual/routing/widget_master_param[Пример]

Если `master-param` не задан, имя параметра пути сгенерируется автоматически.

=== Маршрутизация вложенных страниц

Маршрут вложенных страниц задается атрибутом `route` в месте, вызывающем открытие страницы:
[source,xml]
----
<open-page page-id="childPage" route="/child"/>
----
link:https://n2oapp.net/sandbox/new/manual/routing/page[Пример]
```
http://localhost:8080/#/parent/child
```
, где `/parent` адрес родительской страницы.

Если `route` не задан, маршрутом по умолчанию будет идентификатор кнопки (или действия).

Если дочерняя страница имеет master/detail фильтрацию относительно виджета родительской страницы,
то в маршруте дочерней страницы может присутствовать параметр пути:
[source,xml]
----
<open-page page-id="listContacts" route="/:person_id/contacts"
           master-field-id="id" detail-field-id="person.id"/>
----
link:https://n2oapp.net/sandbox/new/manual/routing/page_master_detail[Пример]
```
http://localhost:8080/#/person/123/contacts
```
, где `123` значение параметра пути `person_id`,
которое соответствует значению поля `id` модели виджета родительской страницы.

Если атрибут `route` для открываемой страницы не задан, или задан без указания параметра пути,
то параметр пути будет определяться через атрибут `master-param`:
[source,xml]
----
<open-page page-id="listContacts"
           master-param="person_id"
           master-field-id="id" detail-field-id="person.id"/>
----
link:https://n2oapp.net/sandbox/new/manual/routing/page_master_param[Пример]
Если `master-param` не задан, имя параметра пути сгенерируется автоматически.

=== Параметры запроса адреса страницы

Помимо параметров пути, адреса страниц могут иметь параметры запроса.
Они задаются в URL как "ключ=значение" после вопросительного знака "?":
```
http://localhost:8080/#/[route]?param1=[value1]&param2=[value2]
```
Параметры запроса обычно задаются через атрибут `param`.

Имя параметра должно быть уникально в рамках одной страницы.
Если имя параметра совпадет с каким-либо из существующих,
то будет использоваться значение параметра, заданного ранее.


Параметрами запроса могут быть предустановленные фильтры вложенной страницы:
[source,xml]
----
<open-page page-id="listContacts" route="/:person_id/contacts">
  <pre-filters>
    <eq field-id="type.id" value="phone" param="contact_type"/>
  <pre-filters>
</open-page>
----
link:https://n2oapp.net/sandbox/new/manual/routing/page_prefilter[Пример]
```
http://localhost:8080/#/persons/123/contacts?contact_type=phone
```
, где `contact_type` параметр запроса, соответствующий значению фильтрации по полю `type.id`.

Параметрами запроса могут быть предустановленные фильтры виджета:
[source,xml]
----
<table query-id="persons" route="/persons">
  ...
  <pre-filters>
    <eq field-id="name" param="name" routable="true"/>
  <pre-filters>
</table>
----
link:https://n2oapp.net/sandbox/new/manual/routing/widget_prefilter[Пример]
```
http://localhost:8080/#/persons?name=Joe
```
, где `name` параметр запроса, соответствующий значению фильтрации по полю `name`.

Атрибут `routable="true"` добавляет фильтр в параметры запроса адреса страницы.
По умолчанию `routable="false"`, это означает, что фильтрация будет происходить по константе или ссылке (требуется атрибут `value`),
и не будет использоваться в параметрах запроса.

Параметрами запроса могут быть пользовательские фильтры:
[source,xml]
----
<table id="main" query-id="persons" route="/persons">
  <filters>
    <input-text id="name"/>
  <filters>
  ...
</form>
----
```
http://localhost:8080/#/persons?main_name=Joe
```
, где `main_name` сгенерированный автоматически параметр запроса,
соответствующий значению фильтрации по полю `name`.

=== Параметры запроса выборки

Маршрут и параметры запроса значений выборки так же можно контролировать.

Маршрут выборки указывается атрибутом `route`:
[source,xml]
----
<query route="/persons">
  ...
</query>
----
link:https://n2oapp.net/sandbox/new/manual/routing/query[Пример]
```
http://localhost:8080/n2o/data/persons
```

Параметрами запроса выборки могут быть фильтры:
[source,xml]
----
<field id="name">
  <filters>
    <like filter-id="name" param="name_like"/>
  <filters>
  ...
</field>
----
link:https://n2oapp.net/sandbox/new/manual/routing/query[Пример]
```
http://localhost:8080/n2o/data/persons?name_like=Joe
```

Параметрами запроса выборки могут быть сортировки:
[source,xml]
----
<field id="name">
  <sorting param="sorting_name"/>
  ...
</field>
----
link:https://n2oapp.net/sandbox/new/manual/routing/query[Пример]
```
http://localhost:8080/n2o/data/persons?sorting_name=asc
```
