== Настройки и локализация
Настройки N2O делятся на настройки клиента, настройки сервера и сообщения локализации.

=== Использование в XML
В любом месте XML файла можно обратиться к настройке через "доллар"
и фигурные скобки: `${property}`, где `property` название настройки.

.Использование настройки в элементе XML
[source,xml]
----
<name>${prop}</name>
----

.Использование настройки в атрибуте XML
[source,xml]
----
<a href="${url}"/>
----

=== Файлы настроек сервера
Значения по умолчанию настройки определяются в файлах `META-INF/n2o.properties`
в ресурсах любого модуля проекта.
Значения задаются в виде "ключ=значение":
----
my.url=https://n2oapp.net/framework
----
Можно использовать SpEL выражение:
----
my.number=#{T(java.lang.Math).random() * 100.0}
----
В SpEL выражениях есть доступ к системным настройкам Java:
----
my.path=#{systemProperties['user.home']}
----
Или к настройкам окружения:
----
my.path=#{envProperties['HOME']}
----

Значения можно переопределить на link:https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html[нескольких уровнях].

=== Файлы локализации
Файлы локализации хранятся как Resource Bundle,
в properties формате в ресурсах любого модуля проекта.
По умолчанию базовое имя файла `messages.properties`.
Базовые имена файлов можно переопределить через настройку `spring.messages.basename`.

Чтобы задать сообщения на другом языке, нужно добавить к базовому имени файла локаль. Например, `messages_en.properties`.
Использовать сообщения локализации можно в любом месте XML файлов конфигураций, точно такое же как и N2O настройки.

=== Файлы настроек клиента
Настройки клиента задаются в формате `json` в файлах `META-INF/config.json`
в ресурсах любого модуля проекта:

.Настройки клиента
[source,json]
----
{
  "name": "Joe"
}
----
В значениях json можно вставлять link:#_Файлы_настроек_сервера[настройки N2O] через "доллар" и фигурные скобки:
[source,json]
----
{
  "src": "${myprops.src}"
}
----

Или можно вставлять значения link:#_Контекст[контекста пользователя]:
[source,json]
----
{
  "user" : {
    "username": "#{username}"
  }
}
----
