global:
  spring:
    useDefaultConsul: false

springServices:
  n2o-sandbox:
    resources:
      limits:
        memory: 700M
        cpu: 500m
      requests:
        memory: 350M
        cpu: 10m
    ingress:
      path: /sandbox