global:
  spring:
    useDefaultConsul: false

springServices:
  n2o-sandbox-${FORMATTED_VERSION}:
    ingress:
      path: /sandbox
    env:
      SPRING_CONFIG_IMPORT: "consul:"
  n2o-test-${FORMATTED_VERSION}:
    imageName: n2o/n2o-sandbox
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 10m
    env:
      N2O_SANDBOX_URL: https://sandbox.n2oapp.net/
      SPRING_CONFIG_IMPORT: "consul:"
      N2O_SANDBOX_TEMPLATE_CATEGORIES: "/menu/tests.json"
      N2O_SANDBOX_PROJECT_SEARCH_FOLDERS: "/autotest"
    replicaCount: 1
    contextPath: tests
    ingress:
      path: /tests