global:
  spring:
    useDefaultConsul: false

springServices:
  demo:
    imageName: n2o/demo
    resources:
      limits:
        memory: 1000Mi
        cpu: 300m
    replicaCount: 1
    contextPath: demo
    ingress:
      path: /demo
  n2o-sandbox:
    ingress:
      path: /sandbox
  n2o-test:
    imageName: n2o/n2o-sandbox
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
    env:
      N2O_SANDBOX_URL: https://sandbox.n2oapp.net/
      SPRING_PROFILES_ACTIVE: test
      SPRING_CONFIG_IMPORT: "consul:"
    replicaCount: 1
    contextPath: tests
    ingress:
      path: /tests