global:
  spring:
    useDefaultConsul: false

springServices:
  demo-${FORMATTED_VERSION}:
    imageName: n2o/demo
    resources:
      limits:
        memory: 1000Mi
        cpu: 300m
    replicaCount: 1
    contextPath: demo
    ingress:
      path: /demo
  n2o-sandbox-${FORMATTED_VERSION}:
    ingress:
      path: /sandbox