global:
  spring:
    useDefaultConsul: false

springServices:
  demo:
    imageName: n2o/demo
    resources:
      limits:
        memory: 1000Mi
        cpu: 300m
      requests:
        memory: 300M
        cpu: 10m
    replicaCount: 1
    contextPath: demo
    ingress:
      path: /demo
  n2o-sandbox:
    ingress:
      path: /sandbox
  n2o-test:
    imageName: n2o/n2o-sandbox
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 300M
        cpu: 10m
    env:
      N2O_SANDBOX_URL: https://sandbox.i-novus.ru/
      SPRING_CONFIG_IMPORT: "consul:"
      N2O_SANDBOX_TEMPLATE_CATEGORIES: "/menu/tests.json"
      N2O_SANDBOX_PROJECT_SEARCH_FOLDERS: "/autotest"
    replicaCount: 1
    contextPath: tests
    ingress:
      path: /tests