global:
  imageTag: "${docker.image.tag}"
  spring:
    env:
      SPRING_CLOUD_CONSUL_CONFIG_PREFIX: n2o-framework
      SPRING_CLOUD_CONSUL_CONFIG_FORMAT: yaml

springServices:
  n2o-sandbox-7-27:
    imageName: n2o/n2o-sandbox
    resources:
      limits:
        memory: 800M
        cpu: 500m
      requests:
        memory: 400M
        cpu: 10m
    env:
      N2O_SANDBOX_URL: https://sandbox.i-novus.ru/
      SPRING_CONFIG_IMPORT: "consul:"
    replicaCount: 1
    contextPath: sandbox
    ingress:
      path: /sandbox

supportingServices:
  docusaurus-7-27:
    useGlobalRegistry: true
    imageName: n2o/docusaurus
    port: 80
    resources:
      limits:
        memory: 200M
        cpu: 200m
      requests:
        memory: 100M
        cpu: 10m
    replicaCount: 1
    ingress:
      path: /