global:
  imageTag: "${docker.image.tag}"
  spring:
    env:
      SPRING_CLOUD_CONSUL_CONFIG_PREFIX: n2o-framework

springServices:
  n2o-sandbox:
    imageName: n2o/n2o-sandbox
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
    env:
      N2O_SANDBOX_URL: https://sandbox.n2oapp.net/
      SPRING_CONFIG_IMPORT: "consul:"
    replicaCount: 1
    contextPath: sandbox
    ingress:
      path: /sandbox

supportingServices:
  docusaurus:
    useGlobalRegistry: true
    imageName: n2o/docusaurus
    port: 80
    resources:
      limits:
        memory: 256Mi
        cpu: 150m
    replicaCount: 1
    ingress:
      path: /