global:
  imageTag: "${docker.image.tag}"

springServices:
  n2o-sandbox:
    imageName: n2o/n2o-sandbox
    resources:
      limits:
        memory: 512Mi
        cpu: 300m
    env:
      N2O_SANDBOX_URL: https://sandbox.n2oapp.net/
    replicaCount: 1
    contextPath: sandbox
    ingress:
      path: /sandbox

supportingServices:
  docusaurus:
    useGlobalRegistry: true
    imageName: n2o/docusaurus
    port: 80
    resources:
      limits:
        memory: 256Mi
        cpu: 150m
    replicaCount: 1
    ingress:
      path: /

mongodb:
  networkPolicy:
    enabled: false
  pdb:
    create: false