springServices:
  demo:
    imageName: n2o/demo
    resources:
      limits:
        memory: 1000Mi
        cpu: 300m
    replicaCount: 1
    contextPath: demo
    ingress:
      path: /demo
  n2o-sandbox:
    ingress:
      path: /sandbox
    env:
      MONGO_HOST: 'sandbox-mongodb'
      MONGO_PASSWORD: "passwd"
  n2o-test:
    imageName: n2o/n2o-sandbox
    resources:
      limits:
        memory: 512Mi
        cpu: 300m
    env:
      N2O_SANDBOX_URL: https://sandbox.n2oapp.net/
      SPRING_PROFILES_ACTIVE: test
    replicaCount: 1
    contextPath: tests
    ingress:
      path: /tests

mongodb:
  persistence:
    storageClass: nfs-retain
    enabled: true
    size: '2Gi'
  auth:
    rootPassword: "passwd"
  service:
    nameOverride: 'sandbox-mongodb'