global:
  spring:
    useDefaultConsul: false

springServices:
  n2o-sandbox-${FORMATTED_VERSION}:
    resources:
      limits:
        memory: 400M
        cpu: 300m
      requests:
        memory: 100M
        cpu: 10m
    ingress:
      path: /sandbox
