springServices:
  n2o-sandbox:
    ingress:
      path: /sandbox
    env:
      MONGO_HOST: 'sandbox-mongodb'
      MONGO_PASSWORD: "passwd"

supportingServices:
  docusaurus:
    useGlobalRegistry: true
    imageName: n2o/docusaurus
    port: 80
    resources:
      limits:
        memory: 256Mi
        cpu: 150m
    replicaCount: 1
    ingress:
      path: /

mongodb:
  persistence:
    enabled: true
    size: '1Gi'
  auth:
    rootPassword: "passwd"
  service:
    nameOverride: 'sandbox-mongodb'