global:
  spring:
    useDefaultConsul: false

springServices:
  demo:
    imageName: n2o/demo
    resources:
      limits:
        memory: 300M
        cpu: 300m
      requests:
        memory: 100M
        cpu: 10m
    replicaCount: 1
    contextPath: demo
    ingress:
      path: /demo
  n2o-sandbox:
    resources:
      limits:
        memory: 400M
        cpu: 300m
      requests:
        memory: 200M
        cpu: 10m
    ingress:
      path: /sandbox