springServices:
  demo:
    imageName: n2o/demo
    resources:
      limits:
        memory: 1000Mi
        cpu: 300m
    replicaCount: 1
    contextPath: demo
    ingress:
      path: /demo
  n2o-sandbox:
    ingress:
      path: /sandbox
    env:
      MONGO_HOST: 'sandbox-mongodb'
      MONGO_PASSWORD: "passwd"

mongodb:
  persistence:
    enabled: true
    size: '1Gi'
  auth:
    rootPassword: "passwd"
  service:
    nameOverride: 'sandbox-mongodb'