global:
  spring:
    useDefaultConsul: false

springServices:
  demo-7-27:
    imageName: n2o/demo
    resources:
      limits:
        memory: 600M
        cpu: 300m
      requests:
        memory: 400M
        cpu: 10m
    replicaCount: 1
    contextPath: demo
    ingress:
      path: /demo
  n2o-sandbox-7-27:
    resources:
      limits:
        memory: 1300M
        cpu: 300m
      requests:
        memory: 400M
        cpu: 10m