global:
  spring:
    useDefaultConsul: false

springServices:
  n2o-sandbox-${FORMATTED_VERSION}:
    ingress:
      path: /sandbox

supportingServices:
  docusaurus-${FORMATTED_VERSION}:
    useGlobalRegistry: true
    imageName: n2o/docusaurus
    port: 80
    resources:
      limits:
        memory: 256Mi
        cpu: 150m
    replicaCount: 1
    ingress:
      path: /