= Кодекс поведения

Как участники и основная команда проекта N~2~O Framework, мы обязуемся уважать всех,
кто вносит свой вклад в развитие N~2~O Framework, публикуя сообщения об ошибках,
обновляя документацию, создавая заявки, решая заявки и любые другие действия.

Общение в GitHub по проекту N~2~O Framework должно быть конструктивным и уважительным.
В общении неприемлимы троллинг, публичные или частные
преследования, личные оскорбления или другие непрофессиональные действия.

Мы обещаем проявлять вежливость и уважение ко всем, кто участвует в этом проекте,
независимо от пола, гендерной идентичности, сексуальной ориентации, ограниченности
возможностей, возраста, расы, этнической принадлежности, религии или уровня опыта.
Мы ожидаем, что любой, кто вносит свой вклад в проект N~2~O Framework, сделает то же самое.

Если какой-либо член сообщества нарушает этот кодекс поведения, команда
проекта N~2~O Framework может предпринимать действия, удаляя запросы, комментарии
и PR или блокируя учетные записи, если сочтет это целесообразным.

Если вы подвергаетесь или становитесь свидетелем неприемлемого поведения,
или у вас есть какие-либо другие проблемы, пожалуйста, напишите нам по адресу
n2o@i-novus.ru.
