= Contribution Guide N~2~O Framework
:toc-title: Содержание

Благодарим Вас за то, что вы нашли время внести свой вклад в развитие N~2~O Framework.
Данная документация поможет Вам сделать это быстрее и качественнее.

== Правила
Помогите нам сохранить N~2~O Framework открытым.
Пожалуйста, прочитайте и следуйте нашему
link:#_Кодекс_поведения[Кодексу поведения].

== Как внести свой вклад

=== Обсуждать
Если у вас есть вопрос, поищите в https://ru.stackoverflow.com/[stackoverflow],
возможно кто-то уже задавался аналогичным вопросом.
Если не найдете подходящие обсуждение, начните новое.

Если вы считаете, что ваш вопрос это скорее всего баг или доработка, то
поищите в существующих запросах.

=== Создавать заявки
Сообщение о проблеме или запрос функции - отличный способ внести свой вклад.
Ваши вопросы, обсуждения и заявки обеспечивают постоянный поток идей,
что позволяет развивать N~2~O Framework.
Однако, прежде чем создавать заявку, пожалуйста, поищите аналогичный запрос
в обсуждениях и заявках.

Если вы создаете заявку после обсуждения в https://ru.stackoverflow.com/[stackoverflow],
пожалуйста, развернуто опишите требования в заявке, вместо того, чтобы просто ссылаться
на stackoverflow.
Система отслеживания заявок является важным местом записи обсуждений дизайна
и должна быть самодостаточной.


=== Исправлять ошибки
Если вы завели заявку на баг и знаете как его исправить самостоятельно, вы можете
сделать fork проекта, исправить баг и сделать pull request. Но перед этим убедитесь,
что  кто-то другой не делает то же самое.
При исправлении бага обязательно необходимо написать тесты покрывающие данный случай.
В N~2~O Framework есть unit тесты, интеграционные (в модуле n2o-test) и автотесты (в модуле n2o-autotest).

=== Добавлять новый функционал
Если вы завели заявку на добавление нового функционала и хотите сами его добавить, то
предварительно обсудите детали реализации с основной командой N~2~O Framework в комментариях к заявке.
Мы старемся оперативно реагировать на заявки и обсуждения.


Так же при выполнении задач (фикс багов или добавлении функциональности)

В `Frontend` части просим вас:

- писать примеры в Storybook, учитывая, что
** должны быть показаны основные фичи компонента
** таблица PropTypes должна быть заполненной, для этого должны быть заполнены propTypes компонента,
и над каждым из них необходимо написать текстовое пояснение
** пример jsx должен быть заполнен
- писать тесты на весь реализуемый функционал


В `Backend` части просим вас:

- соблюдать https://www.oracle.com/technetwork/java/codeconventions-150003.pdf[Java Code Conventions]
- максимально покрывать все тестами
- при добавлении новых компонентов или атрибутов в `xml api` писать документацию
в Руководство разработчика N~2~O(docs\src\manual), в Справочник по XML API (docs\src\xml)
и Migration Guide(docs\src\migration).
