version: "3.6"

services:
  frontend:
    image: "${DOCKER_REGISTRY}/n2o/demo:${TAG}"
    build:
      context: demo/server
  docusaurus:
    image: "${DOCKER_REGISTRY}/n2o/docusaurus:${TAG}"
    build:
      context: frontend/docs
  n2o-sandbox:
    image: "${DOCKER_REGISTRY}/n2o/n2o-sandbox:${TAG}"
    build:
      context: sandbox/server