version: "3.6"

services:
  n2o-sandbox:
    image: "${DOCKER_REGISTRY}/n2o/n2o-sandbox:${TAG}"
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/sandbox
      - N2O_SANDBOX_URL=https://sandbox.n2oapp.net
      - N2O_ENGINE_MONGODB_CONNECTION_URL=${MONGODB_CONNECTION_URL}
      - SPRING_PROFILES_ACTIVE=test
    ports:
      - "8707:8080"
