version: "3.6"

services:
  frontend:
    image: "${DOCKER_REGISTRY}/n2o/demo:${TAG}"
    ports:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
      placement:
        constraints:
          - node.role == worker
  docusaurus:
    image: "${DOCKER_REGISTRY}/n2o/docusaurus:${TAG}"
    ports:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      placement:
        constraints:
          - node.role == worker
  n2o-sandbox:
    image: "${DOCKER_REGISTRY}/n2o/n2o-sandbox:${TAG}"
    environment:
      - N2O_SANDBOX_URL=https://sandbox.n2oapp.net
      - N2O_ENGINE_MONGODB_CONNECTION_URL=${MONGODB_CONNECTION_URL}
    ports:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints:
          - node.role == worker
