build release stand:
  extends: .build maven
  variables:
    MAVEN_EXTRA_BUILD_OPTIONS: '-Pfrontend,frontend-build,backend,!examples,jacoco,demo,docs,sandbox'
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^release\/.+/ && $CI_PIPELINE_SOURCE == 'web'

release version:
  script:
    - |
      RELEASE_VERSION=$(echo "$CI_COMMIT_REF_NAME" | sed 's|^release/||')
      echo "Release branch: $CI_COMMIT_REF_NAME"
      echo "Release version: $RELEASE_VERSION"
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^release\/.+/ && $CI_PIPELINE_SOURCE == 'web'

deploy release stand:
  extends: .deploy
  environment: "release-7-28"
  needs:
    - release version
  variables:
    K8S_INGRESS_HOST: "n2o-framework-${RELEASE_VERSION//./-}-dev.i-novus.ru"
    K8S_NAMESPACE: "release-${RELEASE_VERSION//./-}"
    HELM_OPTIONAL_VALUES: "-f $HELM_CHART_PATH/values.release.yaml --take-ownership"
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^release\/.+/ && $CI_PIPELINE_SOURCE == 'web'
  tags: [dev]
