build release stand:
  extends: .build maven
  variables:
    MAVEN_EXTRA_BUILD_OPTIONS: '-Pfrontend,frontend-build,backend,!examples,jacoco,demo,docs,sandbox'
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^release\/.+/ && $CI_PIPELINE_SOURCE == 'web'

deploy release stand:
  extends: .deploy
  environment: "release-7-27"
  variables:
    K8S_INGRESS_HOST: "n2o-framework-7-27-dev.i-novus.ru"
    K8S_NAMESPACE: "release-7-27"
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^release\/.+/ && $CI_PIPELINE_SOURCE == 'web'
  tags: [dev]
