== Схема доступа <access>

Тип метаданных:: `access`

Библиотека компонентов::
```
http://n2oapp.net/framework/config/schema/access-2.0
```

Подключение::
[source,xml]
----
<dependency>
  <groupId>net.n2oapp.framework</groupId>
  <artifactId>n2o-access</artifactId>
  <version>${n2o.version}</version>
</dependency>
----

Пример::
[source,xml]
----
<?xml version='1.0' encoding='UTF-8'?>
<access xmlns="http://n2oapp.net/framework/config/schema/access-2.0">
  ...
</access>
----

=== <permission>
Доступ пользователю с определенным полномочием

Атрибуты::
[cols="2,1,4,4"]
|===
|Наименование|Тип|Описание|Значение по умолчанию

|id
|Идентификатор
|Код полномочия
|

|name
|Строка
|Наименование полномочия
|

|===

Тело::
link:#_Точки_доступа[Точки доступа]

Пример::
[source,xml]
----
<access>
  <permission id="something.read">
    ...
  </permission>
</access>
----

=== <role>
Доступ пользователю с определенной ролью

Атрибуты::
[cols="2,1,4,4"]
|===
|Наименование|Тип|Описание|Значение по умолчанию

|id
|Идентификатор
|Код роли
|

|name
|Строка
|Наименование роли
|

|===

Тело::
link:#_Точки_доступа[Точки доступа]

Пример::
[source,xml]
----
<access>
  <role id="admin">
    ...
  </role>
</access>
----

=== <user>
Доступ определенному пользователю

Атрибуты::
[cols="2,1,4,4"]
|===
|Наименование|Тип|Описание|Значение по умолчанию

|username
|Строка
|Имя пользователя
|

|===

Тело::
link:#_Точки_доступа[Точки доступа]

Пример::
[source,xml]
----
<access>
  <user username="admin">
    ...
  </user>
</access>
----

=== <authenticated>
Доступ аутентифицированным пользователям

Тело::
link:#_Точки_доступа[Точки доступа]

Пример::
[source,xml]
----
<access>
  <authenticated>
    ...
  </authenticated>
</access>
----

=== <anonymous>
Доступ анонимным пользователям

Тело::
link:#_Точки_доступа[Точки доступа]

Пример::
[source,xml]
----
<access>
  <anonymous>
    ...
  </anonymous>
</access>
----

=== <permit-all>
Доступ всем пользователям

Тело::
link:#_Точки_доступа[Точки доступа]

Пример::
[source,xml]
----
<access>
  <permit-all>
    ...
  </permit-all>
</access>
----
