== Точки доступа

Библиотека компонентов::
```
http://n2oapp.net/framework/config/schema/access-point-2.0
```

=== <object-access>
Точка доступа к данным объекта

Атрибуты::
[cols="2,1,4,4"]
|===
|Наименование|Тип|Описание|Значение по умолчанию

|object-id
|Идентификатор
|Объект, к которому даётся доступ
|

|operations
|Идентификаторы, через запятую
|Операции объекта, к которым даётся доступ.
Можно использовать символ `*` (звездочка) для доступа ко всем операциям.
Если операции не указаны, доступ даётся только на чтение.
|

|===

Тело::
link:#_Предустановленная_фильтрация_pre_filters[Фильтры доступа]

Пример::
[source,xml]
----
<object-access object-id="something" operations="update">
  <eq field-id="type" value="1"/>
</object-access>
----

=== <url-access>
Точка доступа к URL адресам.

Атрибуты::
[cols="2,1,4,4"]
|===
|Наименование|Тип|Описание|Значение по умолчанию

|pattern
|Строка
|Шаблон URL, которому даётся доступ.
Можно использовать символ `*` (звездочка) для доступа ко всем подмножествам пути.
|

|===

Пример::
[source,xml]
----
<url-access pattern="/users/**"/>
----

=== <page-access>
Точка доступа к странице.

Атрибуты::
[cols="2,1,4,4"]
|===
|Наименование|Тип|Описание|Значение по умолчанию

|page-id
|Идентификатор
|Страница к которой даётся доступ
|

|===

Пример::
[source,xml]
----
<page-access page-id="users"/>
----
