== Провайдеры данных

=== Стандартные провайдеры
Библиотека компонентов::
```
http://n2oapp.net/framework/config/schema/data-provider-1.0
```
==== <sql>
Вызов SQL запросов.

Атрибуты::
[cols="2,1,4,4"]
|===
|Наименование|Тип|Описание|Значение по умолчанию

|data-source
|Строка
|Jndi имя jdbc источника данных
|Основной DataSource приложения

|file
|Строка
|Путь к файлу .sql в ресурсах проекта
|

|row-mapper
|map, index
|Способ получения значений из jdbc в запросах sql
|map

|connection-url
|Строка
|URL подключения к базе данных
|

|user
|Строка
|Имя пользователя
|

|password
|Строка
|Пароль
|

|driver
|Строка
|JDBC драйвер
|

|===


Тело::
SQL запрос.

[NOTE]
В запросе могут быть использованы плейсхолдеры через "двоеточие".

Пример::

[source,xml]
----
<sql>
UPDATE mytable SET :params WHERE id = :id;
</sql>
----
[NOTE]
Плейсхолдер `:params` собирается по телу входящих параметров операции.

.SQL запрос для <query>
[source,xml]
----
<query>
  <list>
    <sql>
      SELECT :select
      FROM mytable :join
      WHERE :filters
      ORDER BY :sorting
      OFFSET :offset
      LIMIT :limit
    </sql>
  </list>
</query>
----

[NOTE]
Плейсхолдеры `:select`, `:filters`, `:sorting`, `:join`, `:limit`, `:offset` собираются по критериям выборки.


==== <mongodb>
Вызов запросов к MongoDb.

Атрибуты::
[cols="2,1,4,4"]
|===
|Наименование|Тип|Описание|Значение по умолчанию

|connection-url
|Строка
|Адрес подключения
|

|database-name
|Строка
|Имя базы данных
|

|collection-name
|Строка
|Имя коллекции документов
|

|operation
|find insertOne updateOne deleteOne deleteMany countDocuments
|Операция, выполняемая провайдером
|

|===

.Запрос к MongoDb для <query>
[source,xml]
----
<query>
  <list>
    <mongodb connection-url="mongodb:/testurl"
           database-name="dbName"
           collection-name="user"
           operation="find"/>
  </list>
</query>
----

==== <rest>
Вызов REST запросов.

Атрибуты::
[cols="2,1,4,4"]
|===
|Наименование|Тип|Описание|Значение по умолчанию

|method
|get, post, put, delete
|Http метод запроса
|get

|filters-separator
|Строка
|Разделитель между фильтрами
|&amp;

|sorting-separator
|Строка
|Разделитель между сортировками
|&amp;

|select-separator
|Строка
|Разделитель между столбцами
|&amp;

|join-separator
|Строка
|Разделитель между присоединёнными таблицами
|&amp;

|content-type
|Строка
|Тип контента
|application/json

|proxy-host
|Строка
|Адрес прокси
|

|proxy-port
|Строка
|Порт прокси
|

|===

Тело::
Запрос REST

[NOTE]
В запросе могут быть использованы плейсхолдеры в фигурных скобках.


Пример::
[source,xml]
----
<rest method="put">
  /myservice/myentity/{id}
</rest>
----

.REST запрос для <query>
[source,xml]
----
<query>
  <list result-mapping="content" count-mapping="totalElements">
    <rest method="get" filters-separator=";">
/myservice/myentity/findAll;{filters}?{sortings}&amp;offset={offset};&amp;limit={limit}
    </rest>
  </list>
</query>
----

.Результат REST запроса для <query>
[source,json]
----
{
  "content" : [{}, {}, ...],
  "totalElements" : 100500
}
----

[NOTE]
Плейсхолдеры `{select}`, `{filters}`, `{sorting}`, `{join}`, `{limit}`, `{offset}`, `{page}` собираются по критериям выборки.

==== <java>
Вызов java методов.

[NOTE]
Если не указан IoC контейнер (Spring, EJB), то будет вызов static метода.

Атрибуты::
[cols="2,1,4,4"]
|===
|Наименование|Тип|Описание|Значение по умолчанию

|class
|Строка
|Полное имя java класса
|Из атрибута `service-class` в объекте

|method
|Строка
|Имя java метода
|

|===

Пример::
[source,xml]
----
<java
  class="com.example.MyService"
  method="calcSum">
  <arguments>
      <argument name="a" type="primitive"/>
      <argument name="b" type="primitive"/>
  </arguments>
  <spring/>
</java>
----

.Java класс с методом calcSum
[source,java]
----
package com.example;

public class MyService {
    public static int calcSum(int a, int b) {
      return a + b;
    }
}
----

.Вызов java метода для <query>
[source,xml]
----
<query>
  <list count-mapping="count" result-mapping="list">
    <java
      class="com.example.MyService"
      method="getList">
      <arguments>
        <argument
          type="criteria"
          class="com.example.MyCriteria"/>
      </arguments>
    </java>
  </list>
</query>
----

.Java класс с методом getList
[source,java]
----
package com.example;

public class MyService {
    public static List<MyEntity> getList(MyCriteria filters) {
      ...
    }
}
----

[NOTE]
Фильтры, сортировки, паджинация и другие параметры выборки устанавливаются в объект типа `criteria`.
Поддерживаются интерфейсы `org.springframework.data.domain.Pageable`, `org.springframework.data.domain.Sort`, `org.springframework.data.domain.Example`, `net.n2oapp.criteria.api.Criteria`.

===== <arguments>
Аргументы метода.

[NOTE]
Порядок следования XML элементов соответствует порядку следования аргументов метода.

====== <argument>
Аргумент метода.

Атрибуты::
[cols="2,1,4,4"]
|===
|Наименование|Тип|Описание|Значение по умолчанию

|name
|Строка
|Наименование аргумента метода
|

|type
|primitive, class, entity, criteria
|Тип аргумента
|

|class
|Строка
|Полное имя java класса аргумента
|Для `type="primitive"` определяется автоматически.

Для `type="entity"` определяется по атрибуту `entity-class` объекта.

|default-value
|Строка
|Значение по умолчанию
|

|===

===== <spring>
Вызов Spring бинов.


Атрибуты::
[cols="2,1,4,4"]
|===
|Наименование|Тип|Описание|Значение по умолчанию

|bean
|Строка
|Идентификатор Spring бина
|Если не задан `bean`, то будет поиск по `class`.

|===

Пример::
[source,xml]
----
<java method="calc">
  <spring bean="calculator"/>
</java>
----

===== <ejb>
Вызов EJB бинов.

Подключение::
[source,xml]
----
<dependency>
  <groupId>net.n2oapp.framework</groupId>
  <artifactId>n2o-spring-boot-starter</artifactId>
  <version>${n2o.version}</version>
</dependency>
----

Атрибуты::
[cols="2,1,4,4"]
|===
|Наименование|Тип|Описание|Значение по умолчанию

|bean
|Строка
|Идентификатор EJB бина
|

|protocol
|Строка
|Протокол URI
|

|application
|Строка
|Имя ear приложения
|

|module
|Строка
|Имя ejb модуля
|

|distinct
|Строка
|Имя участка
|

|statefull
|true / false
|С состоянием или без
|false

|uri
|Строка
|Адрес remote бина
|Составляется из `protocol`, `application`, `module`, `distinct`, `bean`, `statefull`.

|===

Пример::
[source,xml]
----
<java class="com.example.MyClass" method="mycall">
  <ejb
    protocol="ejb"
    application="myapp"
    module="mymodule"
    bean="mybean"/>
</java>
----

=== JPA
==== <find>
==== <persist>
==== <merge>
==== <remove>
==== <query>

=== Spring Data
Вызов Spring Data сервисов.

Подключение::
[source,xml]
----
<dependency>
  <groupId>net.n2oapp.framework</groupId>
  <artifactId>n2o-engine-spring</artifactId>
  <version>${n2o.version}</version>
</dependency>
----

Библиотека компонентов::
```
http://n2oapp.net/framework/config/schema/spring-data-1.0
```

[NOTE]
Поддерживаются интерфейсы `CrudRepository`, `PagingAndSortingRepository`, `JpaRepository`, `QueryByExampleExecutor`, `JpaSpecificationExecutor`, `QueryDslPredicateExecutor`.

Пример::
[source,xml]
----
<find-all
  service-class="com.example.MyService"
  entity-class="com.example.MyEntity"
  executor="specification"/>
----

.Spring Data сервис
[source,java]
----
public interface MyService extends JpaRepository<MyEntity>, JpaSpecificationExecutor {
  //метод findAll в JpaSpecificationExecutor
}
----

==== Базовые свойства

Атрибуты::
[cols="2,1,4,4"]
|===
|Наименование|Тип|Описание|Значение по умолчанию

|service-class
|Строка
|Класс сервиса
|Из атрибута `service-class` в объекте

|entity-class
|Строка
|Класс целевой сущности
|Из атрибута `entity-class` в объекте

|bean
|Строка
|Идентификатор Spring бина
|Поиск бина по классу.

|executor
|example, specification, querydsl
|Способ задания критериев запроса
|Если не задан, то поиск без критериев.

|===

===== <arguments>
Аргументы метода.
Аналогично аргументам link:#__java[java провайдера].

==== <find-one>
Поиск одного элемента по идентификатору или критериям.

Пример::
[source,xml]
----
<find-one
  service-class="com.example.MyService"
  entity-class="com.example.MyEntity"/>
----

.Spring Data сервис
[source,java]
----
public interface MyService extends JpaRepository<MyEntity> {
  //метод findOne в JpaRepository
}
----


==== <find-all>
Поиск списка (`List`, `Slice`, `Page`) элементов по критериям.

Пример::
[source,xml]
----
<find-all
  service-class="com.example.MyService"
  entity-class="com.example.MyEntity"
  executor="example"/>
----

.Spring Data сервис поиска по Example
[source,java]
----
public interface MyService extends JpaRepository<MyEntity>, QueryByExampleExecutor {
  //метод findAll в QueryByExampleExecutor
}
----

==== <find-by>
Поиск списка (`List`, `Slice`, `Page`) элементов или одного элемента по http://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods.query-creation[не стандартным методам].

Атрибуты::
[cols="2,1,4,4"]
|===
|Наименование|Тип|Описание|Значение по умолчанию

|method
|Строка
|Полное название метода Spring Data сервиса
|

|===

Пример::
[source,xml]
----
<find-by method="findByLastname"
  service-class="com.example.PersonRepository"
  entity-class="com.example.Person">
  <arguments>
    <argument name="lastname" type="primitive"/>
  </arguments>
</find-by>
----

.Spring Data сервис поиска по Lastname
[source,java]
----
public interface PersonRepository extends Repository<Person, Long> {
  List<Person> findByLastname(String lastname);
}
----

==== <count>
Подсчёт количества записей по критериям.

==== <exists>
Определение существования записи по идентификатору или критериям.

==== <save>
Создание или изменение записи.

==== <delete>
Удаление одной записи по идентификатору или критериям.

==== <delete-all>
Удаление списка записей по критериям.

==== <invoke>
Вызов произвольного метода.

Атрибуты::
[cols="2,1,4,4"]
|===
|Наименование|Тип|Описание|Значение по умолчанию

|method
|Строка
|Полное название метода Spring Data сервиса
|

|===

Пример::
[source,xml]
----
<invoke method="close"
  service-class="com.example.MyService">
  <arguments>
    <argument name="id" type="primitive"/>
  </arguments>
</invoke>
----

.Spring Data сервис с методом close
[source,java]
----
public interface MyService extends Repository<MyEntity, Long> {
  void close(Long id);
}
----
