/**
 * Created by emamoshin on 07.06.2017.
 */
export const METADATA_REQUEST = 'n2o/pages/METADATA_REQUEST';
export const METADATA_SUCCESS = 'PAGE_METADATA_SUCCESS';
export const METADATA_FAIL = 'PAGE_METADATA_FAIL';

export const WIDGET_FETCH_REQUEST = 'WIDGET_FETCH_REQUEST';
export const WIDGET_FETCH_SUCCESS = 'WIDGET_FETCH_SUCCESS';
export const WIDGET_RESOLVE_MODEL = 'WIDGET_RESOLVE_MODEL';
export const WIDGET_REMOVE = 'WIDGET_REMOVE';
export const WIDGET_SHOW = 'WIDGET_SHOW';
export const WIDGET_HIDE = 'WIDGET_HIDE';
export const WIDGET_LOADING = 'WIDGET_LOADING';
export const WIDGET_UNLOADING = 'WIDGET_UNLOADING';
export const WIDGET_ALERT_ADD = 'WIDGET_ALERT_ADD';
export const WIDGET_ALERT_REMOVE = 'WIDGET_ALERT_REMOVE';
export const WIDGET_SET_SORT = 'WIDGET_SET_SORT';

export const MODAL_INSERT = 'MODAL_INSERT';
export const MODAL_REMOVE = 'MODAL_REMOVE';

export const MODEL_SET = 'MODEL_SET';
