import PropTypes from 'prop-types'

export const defaultProps = {
    disabled: false,
    loading: false,
    datasource: [],
    parentIcon: '',
    childIcon: '',
    multiselect: false,
    showLine: false,
    filter: '',
    expandBtn: false,
    bulkData: false,
    parentFieldId: 'parentId',
    valueFieldId: 'id',
    labelFieldId: 'label',
    iconFieldId: 'icon',
    imageFieldId: 'image',
    badgeFieldId: 'badge',
    badgeColorFieldId: 'color',
    hasCheckboxes: false,
    prefixCls: 'n2o-rc-tree',
    icon: '',
    childrenFieldId: 'children',
}

export const propTypes = {
    disabled: PropTypes.bool,
    loading: PropTypes.bool,
    datasource: PropTypes.array,
    parentIcon: PropTypes.string,
    childIcon: PropTypes.string,
    multiple: PropTypes.bool,
    showLine: PropTypes.bool,
    filter: PropTypes.string,
    expandBtn: PropTypes.bool,
    bulkData: PropTypes.bool,
    parentFieldId: PropTypes.string,
    valueFieldId: PropTypes.string,
    labelFieldId: PropTypes.string,
    iconFieldId: PropTypes.string,
    imageFieldId: PropTypes.string,
    badgeFieldId: PropTypes.string,
    badgeColorFieldId: PropTypes.string,
    hasCheckboxes: PropTypes.bool,
    prefixCls: PropTypes.string,
    icon: PropTypes.string,
    selectable: PropTypes.bool,
    childrenFieldId: PropTypes.string,
}
