export const defaultProps = {
    disabled: false,
    loading: false,
    datasource: [],
    parentIcon: '',
    childIcon: '',
    multiselect: false,
    showLine: false,
    filter: '',
    expandBtn: false,
    bulkData: false,
    parentFieldId: 'parentId',
    valueFieldId: 'id',
    labelFieldId: 'label',
    iconFieldId: 'icon',
    badgeFieldId: 'badge',
    badgeColorFieldId: 'color',
    hasCheckboxes: false,
    prefixCls: 'n2o-rc-tree',
    icon: '',
    childrenFieldId: 'children',
}
