= Документация по использованию автотестов в N2O

== Описание
Бибилиотека n2o-autotest использует  https://ru.selenide.org/documentation.html[Selenide]

Требования к окружению:
- jdk 11 версии и выше
- браузер Google chrome

== Запуск
Запускать автотесты можно двумя способами:

1) через IntelliJ IDEA (запуская класс автотеста как обычный unit test)

2) через maven, запустив команду verify,
но предварительно необходимо настроить https://maven.apache.org/surefire/maven-failsafe-plugin/[Maven Failsafe Plugin]

== Использование
Для написания автотестов в зависимости проекта необходимо добавить:
[source,xml]
----
<dependency>
    <groupId>net.n2oapp.framework</groupId>
    <artifactId>n2o-autotest</artifactId>
    <version>${n2o.version}</version>
</dependency>
----


Страницы N2O можно тестировать разными способами:

==== Используя паттерн Page Object
Для тестирования страниц в Selenide принято использовать https://selenide.gitbooks.io/user-guide/content/ru/pageobjects.html[PageObject подход].







==== Через api `n2o-autotest`, для этого необходимо:
<1> написать свой класс, который будет наследником AutoTestBase, в котором уже есть настройки для Selenide.
<2> в нем на стадии `@BeforeAll` вызвать `configureSelenide();`
<3> на стадии `@BeforeEach` вызвать `super.setUp();`
<4> переопределить метод `void configure(N2oApplicationBuilder builder)` где в builder добавить все необходимые MetadataPack(это
наборы сервисов для сборки определенных коллекций метаданных)
<5> в методе теста в builder добавить необходимые файлы исходников

Пример автотеста:
[source,xml]
----
public class AlertAT extends AutoTestBase {

    @BeforeAll
    public static void beforeClass() {
        configureSelenide();
    }

    @BeforeEach
    @Override
    public void setUp() throws Exception {
        super.setUp();
    }

    @Override
    protected void configure(N2oApplicationBuilder builder) {
        super.configure(builder);
        builder.packs(new N2oPagesPack(), new N2oHeaderPack(), new N2oWidgetsPack(), new N2oFieldSetsPack(), new N2oControlsPack());
    }

    @Test
    public void testAlert() {
        builder.sources(new CompileInfo("net/n2oapp/framework/autotest/control/alert/index.page.xml"),
                new CompileInfo("net/n2oapp/framework/autotest/blank.header.xml"));

        SimplePage page = open(SimplePage.class);
        page.shouldExists();
        ...
    }
}
----

Если функций описанных в библиотеке недостаточно всегда можно переключиться на "нативное" тестирование через Selenide,
для этого у любого компонента получить SelenideElement, вызвав метод `element()`, и уже у него получить любой объект,
используя селекторы `.$ .$$`. Пример:
[source,xml]
----
Alert alert = page.single().widget(FormWidget.class).snippet(0, Alert.class);
alert.element().$(".inner-message").should(Condition.exist);
----



== Кастомизация
Если на вашей N2O странице встречаются кастомные компоненты, можно написать свою реализацию интерфейса для этого компонента.
Обязательно добавьте свою реализацию в фабрику.
[source,xml]
----
N2oSelenide.setFactory(new ComponentFactory()
                .addCollections(MyRegions.class, MyWidgets.class)
                .addComponents(MyRegion.class, MyLeftRightPage.class));
----

Если api компенента недостаточно, то вы можете его расширить написав свой интерфейс, сделав его наследником исходного.
