= Документация по использованию автотестов в N2O

== Описание
Библиотека n2o-autotest использует  https://ru.selenide.org/documentation.html[Selenide]

Требования к окружению:

- jdk 17 версии и выше

- браузер Google chrome

== Запуск
Запускать автотесты можно двумя способами:

1) через IntelliJ IDEA (запуская класс автотеста как обычный unit test)

2) через maven, запустив команду verify,
но предварительно необходимо настроить https://maven.apache.org/surefire/maven-failsafe-plugin/[Maven Failsafe Plugin]

== Использование
Для написания автотестов необходимо добавить зависимость:
[source,xml]
----
<dependency>
    <groupId>net.n2oapp.framework</groupId>
    <artifactId>n2o-autotest</artifactId>
    <version>${n2o.version}</version>
</dependency>
----

Для тестирования страниц в Selenide принято использовать
https://selenide.gitbooks.io/user-guide/content/ru/pageobjects.html[PageObject] подход.
Рассмотрим пример тестирования вывода сообщения.

index.page.xml:
[source,xml]
----
<?xml version='1.0' encoding='UTF-8'?>
<simple-page xmlns="http://n2oapp.net/framework/config/schema/page-4.0"
             name="Приветственное сообщение">
    <form>
        <datasource object-id="greeting"/>
        <fields>
            <hidden id="id" default-value="1"/>
            <input-text id="name" label="Имя" placeholder="Введите своё имя"/>
        </fields>
        <toolbar place="bottomLeft">
            <button label="Отправить">
                <invoke operation-id="greeting"/>
            </button>
        </toolbar>
    </form>
</simple-page>
----

greeting.object.xml:
[source,xml]
----
<?xml version='1.0' encoding='UTF-8'?>
<object xmlns="http://n2oapp.net/framework/config/schema/object-4.0">
    <operations>
        <operation id="greeting"
                   success-text="Привет, {name}">
            <invocation>
                <test operation="echo"/>
            </invocation>
            <in>
                <field id="name"/>
            </in>
        </operation>
    </operations>
</object>
----

GreetingPage.java - класс описывающий страницу приложения, на основе `SimplePage`
из библиотеки `n2o-autotest`. Это один из подходов расширения страницы:
[source,java]
----
public class GreetingPage {

    private final SimplePage simplePage;

    public GreetingPage() {
        simplePage = N2oSelenide.page(SimplePage.class);
    }

    public void sendName(String name) {
        FormWidget formWidget = simplePage.widget(FormWidget.class);
        InputText inputText = formWidget.fields().field("Имя").control(InputText.class);
        inputText.val(name);
        formWidget.toolbar().bottomLeft().button("Отправить").click();
    }

    public void greetingShouldHave(String text) {
        simplePage.alerts().alert(0).shouldHaveText(text);
    }
}
----

GreetingAT.java:
[source,java]
----
@SpringBootTest(classes = Application.class, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class GreetingAT {
    @LocalServerPort
    private int port;

    private GreetingPage page;

    /**
     * Задание настроек для Selenide
     */
    @BeforeAll
    public static void configure() {
        System.setProperty("chromeoptions.args", "--no-sandbox,--verbose,--whitelisted-ips=''");
        //Включаем возможность запускать браузер в автономном режиме
        headless = true;
        browserSize = "1920x1200";
    }

    /**
     * Открытие страницы
     */
    @BeforeEach
    public void openProtoPage() {
        page = Selenide.open("http://localhost:" + port, GreetingPage.class);
    }

    @Test
    public void checkHelloText() {
        page.sendName("Иван");
        page.greetingShouldHave("Привет, Иван");
    }
}
----


В автотестах можно использовать N2oSelenide из библиотеки `n2o-autotest` - это главный
класс для старта автотестирования страниц N2O с набором статических методов:

1) открытие страницы n2o:
[source,java]
----
N2oSimplePage page = N2oSelenide.open("http://localhost:" + port, N2oSimplePage.class);
----

2) получение открытой страницы:
[source,java]
----
N2oSimplePage page = N2oSelenide.page(N2oSimplePage.class);
----

3) получение открытого модального окна:
[source,java]
----
N2oModal modal = N2oSelenide.modal(N2oModal.class);
Modal defaultModal = N2oSelenide.modal();
----

4) получение открытого drawer:
[source,java]
----
N2oDrawer drawer = N2oSelenide.drawer(N2oDrawer.class);
Drawer defaultDrawer = N2oSelenide.drawer();
----

5) получение любого визуального компонента(Component) для автотестирования:
[source,java]
----
N2oText text = N2oSelenide.component(page.element().$(".n2o-text-field"), N2oText.class);
----

6) получение списка визуальных компонентов(Component):
[source,java]
----
N2oSelenide.collection(element().$$(".n2o-standard-widget-layout"), Widgets.class);
----

7) задание собственной фабрики получения компонентов. Возможные случаи использования:
на проекте есть дополнительный кастомный компонент, например своя ячейка,
или на всем проекте заменен какой-то компонент, например везде используется
расширенный input-text.
[source,java]
----
N2oSelenide.setFactory(new ComponentFactory()
                .addCollections(N2oWidgets.class)
                .addComponents(CustomCell.class));
----

Используя этот класс, можно переписать автотест следующим образом
[source,java]
----
@SpringBootTest(classes = Application.class, webEnvironment =
                SpringBootTest.WebEnvironment.RANDOM_PORT)
public class SimpleGreetingAT {
    @LocalServerPort
    private int port;

    private SimplePage page;

    ...

    @Test
    public void greetingTest() {
        InputText inputText = page.widget(FormWidget.class).fields()
                                  .field("Имя").control(InputText.class);
        inputText.val("Иван");
        page.widget(FormWidget.class).toolbar().bottomLeft()
                     .button("Отправить").click();
        page.alerts().alert(0).shouldHaveText("Привет, Иван");
    }
}
----

== Кастомизация

Если на вашем проекте встречаются кастомные компоненты, можно написать свою
реализацию интерфейса для этого компонента, например `MyWidget` и получить его следующим образом
[source,java]
----
N2oSelenide.component(page.element().$(".n2o-standard-widget-layout"), MyWidget.class);
----

Если функций описанных в библиотеке `n2o-autotest` недостаточно всегда можно переключиться
на "нативное" тестирование через Selenide, для этого у любого компонента
получить SelenideElement, вызвав метод `element()`, и уже у него получить любой объект,
используя селекторы `.$ .$$`. Пример:
[source,java]
----
Alert alert = page.widget(FormWidget.class).fields().field(Alert.class);
alert.element().$(".inner-message").should(Condition.exist);
----
