export const FETCH_START = 'n2o/fetch/START'
export const FETCH_END = 'n2o/fetch/END'
export const FETCH_ERROR = 'n2o/fetch/ERROR'
export const FETCH_CANCEL = 'n2o/fetch/CANCEL'
export const FETCH_ERROR_CONTINUE = 'n2o/fetch/ERROR_CONTINUE'
