/**
 * Created by emamoshin on 02.11.2017.
 */
export const REGISTER = 'n2o/widgets/REGISTER'
export const DATA_REQUEST = 'n2o/widgets/DATA_REQUEST'
export const DATA_SUCCESS = 'n2o/widgets/DATA_SUCCESS'
export const DATA_FAIL = 'n2o/widgets/DATA_FAIL'
export const RESOLVE = 'n2o/widgets/RESOLVE'
export const REMOVE = 'n2o/widgets/REMOVE'
export const SHOW = 'n2o/widgets/SHOW'
export const HIDE = 'n2o/widgets/HIDE'
export const ENABLE = 'n2o/widgets/ENABLE'
export const DISABLE = 'n2o/widgets/DISABLE'
export const DISABLE_ON_FETCH = 'n2o/widgets/DISABLE_ON_FETCH'
export const LOADING = 'n2o/widgets/LOADING'
export const UNLOADING = 'n2o/widgets/UNLOADING'
export const ALERT_ADD = 'n2o/widgets/ALERT_ADD'
export const ALERT_REMOVE = 'n2o/widgets/ALERT_REMOVE'
export const SORT_BY = 'n2o/widgets/SORT_BY'
export const CHANGE_SIZE = 'n2o/widgets/CHANGE_SIZE'
export const CHANGE_PAGE = 'n2o/widgets/CHANGE_PAGE'
export const CHANGE_COUNT = 'n2o/widgets/CHANGE_COUNT'
export const CHANGE_FILTERS_VISIBILITY = 'n2o/widgets/CHANGE_FILTER_VISIBILITY'
export const TOGGLE_FILTERS_VISIBILITY = 'n2o/widgets/TOGGLE_FILTER_VISIBILITY'
export const RESET_STATE = 'n2o/widgets/RESET_STATE'
export const SET_WIDGET_METADATA = 'n2o/widgets/SET_WIDGET_METADATA'
export const SET_TABLE_SELECTED_ID = 'n2o/widgets/CHANGE_SELECTED_ID'
export const SET_ACTIVE = 'n2o/widgets/SET_ACTIVE'
export const RESOLVE_DEPENDENCY = 'n2o/widgets/RESOLVE_DEPENDENCY'
