export const TABLE = 'table'
export const FORM = 'form'
export const HTML = 'html'
export const WIREFRAME = 'wireframe'
export const ADVANCED_TABLE = 'advancedTable'
export const TREE = 'tree'
export const LIST = 'list'
export const CHART = 'chart'
