= Документация разработчика N~2~O

== Введение
Документация предназначена помочь разработчикам прикладных проектов самостоятельно разобраться в функциях и возможностях фреймворка N2O.

== Как подключить к проекту
[source,xml]
----
<dependency>
    <groupId>net.n2oapp.framework</groupId>
    <artifactId>docs</artifactId>
    <version>${n2o.version}</version>
    <scope>runtime</scope>
</dependency>
----

Документация будет доступна по адресу `docs/manual` и `docs/xml` относительно контекста приложения.

== Правила написания документации

=== Общие правила
. Наименование фреймворка писать заглавными буквами, так `N2O` в параграфах, и так `N~2~O` в заголовках.
. Использовать единообразную лексику и стилистику текста
. Выделять в тексте однострочные элементы кода `вот так`
. При многострочном коддинге обязательно указывать язык: `[source,lang]`
. Обязательно подписывать картинки и таблицы: `.Подпись к таблице`
. Использовать нотацию `[TIP]` для описания best practice или ссылок на примеры реализаций.
. Использовать нотацию `[NOTE]` для контекстных ссылок на другие документации.
. Использовать нотацию `[IMPORTANT]` и `[WARNING]` для описания ограничений или частых ошибок.
. Не вставлять большой листинг, примеры должны быть контекстными, всё лишнее замалчивать троеточиями

=== Правила документации справочника по XML API
. Справочная документация по XML API имеет строгую иерархию. Она уже сформирована и правки в неё нужно вносить согласованно.
. Каждый раздел, описывающий элемент XML, может иметь следующие подразделы
.. Атрибуты (атрибуты элемента)
.. Элементы (простые элементы с типом `string`, `enum`, `integer` или `boolean`)
.. Тело (если внутри `string` или `any`)
.. Пример
.. Подразделы с вложенными элементами
. При упоминании элементов из другого раздела следует ссылаться на него через `link:#_anchor[text]`
