drop table address if exists;
drop table category if exists;
drop table product if exists;
drop table product_shop if exists;
drop table shop if exists;
create table address (id bigint generated by default as identity, location varchar(255), primary key(id));
create table category (id bigint generated by default as identity, name varchar(255), primary key (id));
create table product (id bigint generated by default as identity, description varchar(255), name varchar(255), price bigint, quantity integer, category_id bigint, primary key (id));
create table product_shop (shop_id bigint not null, product_id bigint not null);
create table shop (id bigint generated by default as identity, name varchar(255), address_id bigint, primary key (id));
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category;
alter table product_shop add constraint FKdrjla9budonk1nufllfjmoc9b foreign key (product_id) references product;
alter table product_shop add constraint FKr2ev3c6j39yeckgsywvr4e02e foreign key (shop_id) references shop;
alter table shop add constraint FKqwhej4gio2sg92f7hmwprpbyi foreign key (address_id) references address;


insert into Category (name) values ('Electronics');
insert into Category (name) values ('Furniture');

insert into Address (location) values ('Казань, пр. Ибрагимова, 56');
insert into Address (location) values ('Казань, ул. Татарстан, 18');
insert into Address (location) values ('Казань, ул. Баумана, 68');
insert into Address (location) values ('Казань, ул. Рахимова, 8');
insert into Address (location) values ('Казань, Сибирский Tракт, 34');
insert into Address (location) values ('Казань, просп. Победы, д. 91');
insert into Address (location) values ('Казань, Московская ул., 2');
insert into Address (location) values ('Казань, ул. Петербургская, 1');
insert into Address (location) values ('Казань, пр. Хусаина Ямашева, 46');
insert into Address (location) values ('Казань, просп. Победы, д. 91');
insert into Address (location) values ('Казань, пр. Ибрагимова, 56');
insert into Address (location) values ('Казань, просп. Победы, д. 141');

insert into Shop (name, address_id) values ('Eldorado', 1);
insert into Shop (name, address_id) values ('Atlant', 2);
insert into Shop (name, address_id) values ('DNS', 3);
insert into Shop (name, address_id) values ('Mebelgrad', 4);
insert into Shop (name, address_id) values ('Mega-Mebel', 5);
insert into Shop (name, address_id) values ('Ашан', 6);
insert into Shop (name, address_id) values ('ЦУМ', 7);
insert into Shop (name, address_id) values ('Кольцо', 8);
insert into Shop (name, address_id) values ('Park House', 9);
insert into Shop (name, address_id) values ('Южный', 10);
insert into Shop (name, address_id) values ('Тандем', 11);
insert into Shop (name, address_id) values ('МЕГА', 12);


insert into Product (name, price, quantity, description, category_id) values ('Phone', 35, 1, 'Motorola Z310', '1');
insert into Product (name, price, quantity, description, category_id) values ('Laptop', 71, 1, 'Lenovo S-2500', '1');
insert into Product (name, price, quantity, description, category_id) values ('TV', 200, 1, 'LG, diagonal: 25', '1');
insert into Product (name, price, quantity, description, category_id) values ('Sega', 20, 1, 'Special offer: additional 5 cartridges!', '1');
insert into Product (name, price, quantity, description, category_id) values ('Smart home', 500, 1, 'Best system to manage your house', '1');
insert into Product (name, price, quantity, description, category_id) values ('Computer', 150, 1, 'Apple iMac 21.5', '1');
insert into Product (name, price, quantity, description, category_id) values ('Smart vacuum cleaner', 100, 1, 'LG VR6270LVM', '1');
insert into Product (name, price, quantity, description, category_id) values ('Microwave oven', 175, 1, 'The best oven!', '1');
insert into Product (name, price, quantity, description, category_id) values ('Climate control', 370, 1, 'Fill you in a tropic', '1');
insert into Product (name, price, quantity, description, category_id) values ('Dishwasher', 210, 1, 'Save your time', '1');
insert into Product (name, price, quantity, description, category_id) values ('Home helper robot', 1350, 1, 'Now you can talk not only with cats or mirror', '1');

insert into Product (name, price, quantity, description, category_id) values ('Sofa', 155, 1, 'Very comfortable', '2');
insert into Product (name, price, quantity, description, category_id) values ('Chair', 50, 1, 'Best place to have a rest', '2');
insert into Product (name, price, quantity, description, category_id) values ('Table', 170, 1, 'Big table for big family', '2');
insert into Product (name, price, quantity, description, category_id) values ('Cupboard', 500, 1, 'Easy fit all your clothe', '2');
insert into Product (name, price, quantity, description, category_id) values ('Mirror', 35, 1, 'Anti-glare', '2');
insert into Product (name, price, quantity, description, category_id) values ('Computer table', 100, 1, 'Standard size', '2');
insert into Product (name, price, quantity, description, category_id) values ('Shelf', 10, 1, 'Big choice', '2');
insert into Product (name, price, quantity, description, category_id) values ('Armchair', 80, 1, 'Soft and style', '2');
insert into Product (name, price, quantity, description, category_id) values ('Bed', 320, 1, 'For two people', '2');
insert into Product (name, price, quantity, description, category_id) values ('Nightstand', 30, 1, 'Small size', '2');
insert into Product (name, price, quantity, description, category_id) values ('Wardrobe', 110, 1, 'For small room', '2');


insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('1', '1');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('1', '2');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('1', '3');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('2', '1');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('3', '3');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('3', '2');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('4', '1');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('5', '3');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('6', '1');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('6', '2');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('6', '3');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('7', '2');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('11', '3');

insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('7', '4');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('11', '5');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('11', '6');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('12', '7');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('14', '8');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('15', '9');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('15', '10');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('16', '12');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('17', '12');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('18', '10');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('19', '9');
insert into PRODUCT_SHOP (PRODUCT_ID, SHOP_ID) values ('20', '8');
