=== Миграция

В этом разделе рассказывается, как мигрировать проект с предыдущих версий N2O Framework.

==== Миграция с 7.15 на 7.16

*Изменения в XML API*

- У ссылок, которые должны открываться внутри приложения необходимо задавть `target=application`.
Ранее он опредлялся автоматически по содержимому ссылки, теперь по умолчанию всегда равен self.
Необходимо найти все ссылки на проекте и проверить какой у них должен быть `target`.

- Прекращена поддержка `object-2.0`. Рекомендуется во всех объектах использовать схему `object-4.0`.


==== Миграция с 7.14 на 7.15

*Изменения в XML API*

- Атрибут `mapping-condition` поля операции переименован в `enabled`.
- Валидации полей теперь работают аналогично валидациям в object-4.0, а не object-3.0, как было раньше.
Таким образом `<in-parameters>` и `<out-parameters>` переименованы в `<in>` и `<out>`, а `<param>` в `<field>`.
- У всех кнопок упраздняются атрибуты `visibility-condition` и `enabled-condition`.
Пока что только на уровне xml. Вместо них рекомендуется использовать атрибуты `visible` и `enabled`.

*Изменения в настройках*

- Настройки n2o.engine.mongodb.connection_url, n2o.engine.mongodb.database_name будут упразднены в следующих версиях,
рекомендуется использовать аналогичные org.springframework.boot.autoconfigure.mongo.MongoProperties
(spring.data.mongodb.uri, spring.data.mongodb.database и т.д.)

==== Миграция с 7.13 на 7.14

*Изменения в XML API*

- Атрибут `backdrop-closable` в `<open-drawer>` заменен на `close-on-backdrop`.

*Изменения в сборке*

- Добавлена зависимость `org.openjdk.nashorn:nashorn-core` для поддержки javaScript вычислений на сервере с java 15
- Повышена минимальная версия java, на которой работает N2O, до 11.

*Изменения функциональности*

- Для фильтрации зависимых виджетов (`depends-on`), необходимо заполнить
`detail-field-id` или прописать `pre-filters`. В прежних версиях фильтрация работала и без `detail-field-id`.

- Убрана неявная фильтрация виджетов, если параметр URL страницы совпадает с `filter-id`
выборки виджета. Например:

[source,xml]
----
<open-page page-id="card" route="/:id/update">
      <path-param name="id" value="{id}"/> <!-- передаем параметр id -->
</open-page>
----

Если на странице `card` в выборке был фильтр `id`, то раньше фильтрация
сработала бы неявно, сейчас этого не произойдет!

Необходимо задать pre-filters на странице `card` явно:

[source,xml]
----
<form query-id="cards">
     ...
     <pre-filters>
         <eq field-id="id" param="id"/> <!-- берем параметр id из URL и фильтруем форму -->
     </pre-filters>
</form>
----

Хорошей практикой будет не давать path параметрам страницы простых имен, таких как `id`, совпадающее с фильтрами выборки. Лучше дать им имена с префиксом сущности: `document_id`.


! Замечание: так как данные изменения, могут повлечь за собой много багов и
усложняют переход на новую версию, введена временная настройка
`n2o.config.filter.old_mode` если указать значение `true`, то фильтрация будет работать
в старом режиме. Данная настройка будет убрана в версии 16.0, поэтому ее использование не желательно.

*Изменения в настройках*

- Добавлена настройка `n2o.config.fail_fast`, которая в значении `false` позволит не падать приложению при отсутствии значения настройки в момент чтения xml файлов.
По умолчанию `true`.

*Изменения в Java API*

- Создан класс `AbstractFilteredPageBinder` для упрощения биндинга конкретных страниц. Пример использования:
[source,java]
````
@Component
class MyPageBinder extends AbstractFilteredPageBinder {
    public MyPageBinder() {
        super("myPage");///Идентификатор конкретной страницы
    }

    @Override
    public Page bind(Page page, BindProcessor p) {
        //Изменение myPage
    }
}
````

==== Миграция с 7.12 на 7.13

*Изменения в XML API*

- Атрибут `rows` `<text-area>` заменен на `max-rows` с сохранением обратной совместимости.

- Удалена автогенерация path-параметров в route.
Теперь использование `detail-field-id`, `master-param`, `master-field-id` при открытии
страниц (`show-modal`, `open-page`, `open-drawer`) не приводит к автоматическому
добавлению параметров в путь. Теперь эти атрибуты автоматически генерируются в query-параметры
и при возвратах назад могут теряться.
Необходимо обратить на это внимание и в местах, где это критично,
явно прописать `route` c `path-param` для сохранения старой маршрутизации.

- В дополнении к `detail-field-id` и `master-field-id` также упраздняется `master-param`
на уровне xml. Необходимо удалить его и указать path-параметры явно.


==== Миграция с 7.11 на 7.12

*Изменения в XML API*

- Регион `line` и филдсет `line` приведены к единому виду.
Вследствие этого аттрибут `name` региона `line` переименован в `label`, а `open` - в `expand`.
Также появилось свойство `has-separator` (по умолчанию `true`), которое позволяет добавить/скрыть горизонтальный делитель.
Чтобы сохранить предыдущее поведение регионов (горизонтальный делитель отсутствовал),
надо везде, где это необходимо, проставить `has-separator="false"`
- Атрибут `label` `<multi-set>` теперь используется для задания глобального заголовка
мультисета. Его старый функционал, позволяющий задавать заголовки дочерних элементов,
был перенесен в атрибут `children-label`.

==== Миграция с 7.10 на 7.11

*Изменения в XML API*

- Введены page-3.0.xsd и region-2.0.xsd, в которых упразднены place у регионов.
- В каждом регионе теперь можно располагать произвольное количество виджетов и вложенных регионов.
- В `<regions>` можно не использовать `<region>` для вложения виджетов и регионов.
Однако он не упраздняется, а может использоваться, как кастомный регион с src.
- В `<tabs>` теперь нельзя напрямую вкладывать виджеты.
Для этого необходимо использовать дочерний элемент `<tab>`,
в которые теперь можно вкладывать, как виджеты, так и регионы.
- Использование `<line>` создает только одну линию
(вложенные виджеты теперь не порождают много линий).
Для порождения второй линии создайте еще одну `<line>`.
- Панель `<panel>` работает аналогичным с `<line>` образом.
- Имя региона теперь задается не именем вложенного виджета, а специальным атрибутом `name`
в случае `<line>`, `<tab>`. Атрибут `title` по прежнему используется для задания имени
региона `<panel>`.
- ! Нарушение обратной совместимости при использовании page-2.0 и region-1.0.
При использовании региона `<line>` не получится вложить больше одного виджета в `<line>`
и породить несколько линий.
- Добавлена проверка наличия `path-param` в `open-page`, `drawer`, `show-modal`, если они
используются в `route`. Необходимо проверить на проекте все роуты, в которых встречаются
`path` параметры, например `route="/:id/update"` и проверить прописан ли тег `<path-param name="id" value="..."/>`.
 Можно все случаи найти поиском `/:`.

*Изменения в сборке*

- Введена поддержа мультиязычности, теперь возможно локализовать любой текст, используя
плейсхолдер `${name}`.
- появились настройки:
`n2o.i18n.enabled` - доступность переключения языка, по умолчанию false.
`n2o.i18n.default-locale` - locale по умолчанию.
- Message bundle N2O лежат в `n2o_api_messages, n2o_config_messages, n2o_rest_messages`
Message bundle приложения в messages. Для добавления дополнительных необходимо
переопределить настройку `spring.messages.basename`, не забыв указать message bundle N2O.

==== Миграция с 7.9 на 7.10

*Изменения в XML API*

- Атрибут `param` в параметрах операции (`<in><field>`) больше не имеет значения по умолчанию.
Чтобы принять значение, переданное в параметрах URL, необходимо явно прописать `param`.
- Атрибут `param` в параметрах операции (`<in><field>`) больше не распространяется на данные, переданные в `<form-param>`.
Чтобы в параметрах операции принять значение, переданное в `<form-param>`, достаточно указать `<field id>` равное `<form-param name>`.
- Атрибут `name` в `<form-param>` заменен на `id` с сохранением обратной совместимости.
- Добавлена проверка наличия `path-param` в `invoke`, если они используются в `route`.

*Изменения в сборке*

- Изменена генерация route для invoke, теперь id записи не добавляется автоматически.
Если необходим идентификатор или любой другой параметр в url запроса, то необходимо прописать
атрибут route в xml.

==== Миграция с 7.8 на 7.9

*Изменения в настройках*

- Упразднено значение "руб. " по умолчанию для суффикса `<input-money>`. Теперь значением по умолчанию
для суффикса и префикса является "".
Дополнительно добавлены настройки `n2o.api.control.input.money.prefix` и `n2o.api.control.input.money.suffix`.

- Добавлена настройка `n2o.api.default.page.show_title` значение по умолчанию false

==== Миграция с 7.7 на 7.8

*Изменения в сборке*

- Переход с jdom на jdom2
- Переход с commons-lang на commons-lang3
- Из n2o-spring-boot-starter удалена зависимость net.sf.ehcache:ehcache.
Она не требуется для работы фреймворка, но для оптимизации рекомендуется ставить ее в прикладных приложениях.


==== Миграция с 7.6 на 7.7

*Изменения в настройках*

- Настройка `n2o.ui.homepage.id` заменена на `n2o.header.homepage.id`.
- Настройка `n2o.project-name` заменена на `n2o.header.title`.
- Настройка `n2o.api.default.header.fixed` заменена на `n2o.header.fixed`.
- Настройка `n2o.api.default.header.collapsed` заменена на `n2o.header.collapsed`.


==== Миграция с 7.5 на 7.6

*Изменения в XML API*

- Добавлен новый функционал для передачи параметров в url открываемой страницы -
тэги `<path-param>` и `<query-param>`.
- Упразднены `<pre-filters>` в `show-modal` и `open-page`, пока на уровне xml,
в следующих версиях будет убрано совсем. Вместо них необходимо использовать `<query-param>` и `<path-param>`.
- Упразднены `master-field-id` и `detail-field-id` в `show-modal` и `open-page`,
пока на уровне xml, в следующих версиях будет убрано совсем.
Вместо них необходимо использовать `<path-param>` и `<pre-filters>` в виджете на открываемой странице.
- Переименованы <in-parameters> и <out-parameters> в <in> и <out>, а <param> в <field>
- Упразднен `layout` у <page>. Вместо него необходимо использовать src с указанием класса страницы.


==== Миграция с 7.4 на 7.5

*Изменения в сборке*

- Модули `n2o-engine-ejb`, `n2o-config-ehcache`, `n2o-config-hazelcast` удалены.
Вместо них нужно использовать зависимости `spring-jdbc`, `ejb-api`, `ehcache`, `hazelcast` соответственно.

*Изменения в настройках*

- Вместо `n2o.access.N2oObjectAccessPoint.default=false` используется настройка `n2o.access.deny_objects=true`,
и другие настройки:
+
```
#Запрещен ли доступ к объектам по умолчанию
n2o.access.deny_objects=true
#Запрещен ли доступ к страницам по умолчанию
n2o.access.deny_pages=false
#Запрещен ли доступ к url по умолчанию
n2o.access.deny_urls=false
```

*Изменения в XML API*

- Пустая строка в контексте ведет себя аналогично null (отсутствие значения)
- В `<input-select-tree>` полностью удален `<grouping-nodes>`, атрибуты из `<inheritance-nodes>` перенесены в `<input-select-tree>`
- Атрибут `search-field-id` в списковых компонентах переименован в `search-filter-id`

==== Миграция с 7.3 на 7.4

*Изменения в настройках*

- Переименованы следующие настройки: `n2o.ui.header.id` в `n2o.header.id`
- Добавлена настройка `n2o.access.strict_filtering`, означающая строго ли проверяется фильтрация.
Если `true`, то при указании фильтра в настройках доступа запрос за данными без этого фильтра выполняться не будет.
- Формат дат в модели клиента изменился с `DD.MM.YYYY HH:mm:ss` на ISO `YYYY-MM-DDTHH:mm:ss`.
Значения по умолчанию для компонентов `<date-time>`, `<date-interval>` нужно задавать в новом формате.

==== Миграция с 7.1 на 7.2

*Изменения в сборке*

- Фреймворк переведен на Spring Boot 2.1.1. Для запуска в качестве WAR требуется Tomcat 8+
- Добавлена совместимость с OpenJDK 11
- В файлах config.json все вставки плейсхолдеров должны быть внутри кавычек, например, `"roles":"#{roles}"`

*Изменения в XML API*

- В адресации страниц больше нет адреса основного виджета по умолчанию.
Например, вместо `documents/main`, будет `/documents`.
Но можно вернуть явно указав для виджета атрибут `route`

==== Миграция с 7.0 на 7.1

*Изменения в сборке*

- Вместо React компонента `TableWidget` используется `AdvancedTableWidget` (`n2o.api.widget.table.src`)
- Удалён модуль `n2o-header`
- Удалён модуль `n2o-config-audit`

*Изменения в XML API*

- Для перерисовки опций в компонентах `<radio-group>`, `<checkbox-group>` вместо `depends-on` необходимо использовать `<dependencies>` `<fetch>`.
- Фильтры доступа в `access-schema-1.0` больше не считываются, вместо них необходимо использовать `<object-filters>` в `access-2.0`
- Для `query-4.0` больше нет автогенерации тела фильтров и элементов `<select/>` и `<sorting/>`

*Изменения в Java API*

- Изменено API у `MetadataBinder`, вместо `CompileProcessor` используется `BindProcessor`
- Изменено API у `SourceValidator`, в метод validate добавлен аргумент `ValidationProcessor`
- Изменено API у метода execute в `PipelineOperation`, добавлены аргументы `BindProcessor`, `ValidationProcessor`
- Удалены deprecated классы из пакета `net.n2oapp.framework.api.metadata.local.*`
- Удалены deprecated классы `AuthorizationApi`, `SimpleAuthorizationApi`, `DataAccessChecker`, `UrlFilter`

==== Миграция с 6.0 на 7.0

*Изменения в сборке*

- N2O теперь встраивается в Spring Boot приложение с помощью стартера `n2o-spring-boot-starter`
- Статические ресурсы клиента N2O теперь нужно собирать самостоятельно, либо подключить модуль `n2o-web`
- Для работы с SQL из N2O теперь необходимо подключить `n2o-engine-sql` модуль
- Вместо `n2o-build.properties` необходимо использовать `application.properties`

*Изменения в XML API*

- Во всех `<set-value-expression>` в теле необходимо в конце явно вызывать команду return с тем значением, которое хотели установить
- Если `<set-value-expression>` возвращает `undefined`, то значение не будет установлено
- Во всех dependency условиях должны быть javaScript expression, а не statements. Т.е. запрещены многострочные команды, объявление переменных и т.п.
- Глобальные линки упразднены. Вместо них используется ссылки на модели с URI синтаксисом
- Стандартный формат даты и времени в REST изменился с `dd.MM.yyyy HH:mm` на ISO `YYYY-MM-DDTHH:mm:ss.sssZ`
- Вёрстка всех компонентов формы стала растягиваемой вместо фиксированной. Т.е. используется grid система bootstrap. Ширина всех полей теперь по умолчанию 100%. Если на одной строке `<row>` несколько полей, то их ширина пропорциональна. Разные пропорции можно задать с помощью bootstrap классов `.col-md-x`, где x число от 1 до 12
- Упразднена схема `n2o-widget-1.0`, `n2o-widget-2.0`. Нужно использовать `widget-4.0`
- Упразднена схема `fieldset-1.0`. Нужно использовать `fieldset-4.0`
- Упразднена схема `action-invocation-1.0`. Нужно использовать `n2o-invocation2-2.0`
- Упразднена схема `query-1.0` и `query-2.0`. Нужно использовать `query-3.0` или `query-4.0`
- Упразднен `multi-clasifier`. Вместо него используйте `select` с `type=multi` или `input-select` с `type=multi`
- У формы упразднён `edit` элемент. Нужно создавать кнопки самостоятельно
- В схеме `n2o-widget-3.0` не поддерживаются настройки `<settings/>`.  Необходимо использовать `n2o-widget-4.0`
- Фильтры в схеме доступа `access-1.0` больше не поддерживаются. Необходимо использовать `access-2.0`

*Изменения в Java API*

- `LocalizationHolder` и библиотека i18n больше не используются. Для локализации нужно использовать бин `MessageSourceAccessor`.
- `N2oBusinessException` устарел, вместо него рекомендуется использовать `N2oUserException`
- `N2oException` принимает и сообщения и код сообщений в качестве message (код из файлов message source). Сообщения могут быть шаблонизированы через плейсхолдеры {0}.
- Полностью изменился процесс компиляции метаданных. Устарели классы `GlobalMetadataStorage`, `MetadataStorage`, `UserMetadataStorage`, `N2oCompiler` и все его наследники, `CompileContext`, `MetadataValidator`, `Transformer` и др.
- Все методы API вместо класса `N2oMetadata` используют интерфейс `SourceMetadata`.
- Интерфейс `N2oEvent` сменил название на `N2oAction`, класс  `AbstractEvent` сменил название на `N2oAbstractAction`, класс  `Custom` сменил название на `N2oCustomAction`, класс `InvokeEvent`   сменил название на `N2oInvokeAction`, класс `ShowModal` сменил название на `N2oShowModal`, интерфейс `PageIdAwareCompileEvent` сменил название на `PageIdAwareCompileAction`
- Все events перенесены из `net.n2oapp.framework.api.metadata.event` в `net.n2oapp.framework.api.metadata.event.action`
- Класс `N2oFieldSet` перенесен из `net.n2oapp.framework.api.metadata.global.view.widget` в `net.n2oapp.framework.api.metadata.global.view.fieldset`, `N2oFieldSet`  стал абстрактным. Для реализации нужно выбрать один из следующих вариантов: `N2oSetFieldSet`, `N2oLineFieldSet`, `N2oCheckboxLineFieldSet`
- Упразднён процессинг SQL, REST. Вместо этого нужно переопределять соответствующие бины.
- В интерфейсе `SourceLoader` метод `read` переименован в `load`.
- Класс `JavaSourceReader` переименован в `JavaSourceLoader`.
- `N2oEvent` стал классом и наследником Spring `ApplicationEvent`, в его конструкторе появился аргумент source, в который нужно передать инициатора события (publisher)
